#!/bin/sh
#
#      $Id$
#
#########################################################################
#									#
#			   Copyright (C)  2002				#
#	     			Internet2				#
#			   All Rights Reserved				#
#									#
#########################################################################
#
#	File:		bootstrap
#
#	Author:		Jeff Boote
#			Internet2
#
#	Date:		Wed Apr 17 13:15:07 EDT 2002
#
#	Description:	
#			This script is used to bootstrap the autobuild
#			process.
#
#			RUNNING THIS SCRIPT IS NOT RECOMMENDED
#			(You should just use the "configure" script
#			that was bundled with the distribution if
#			at all possible.)
#

if test -x I2util/bootstrap; then
	echo
	echo "## I2util/bootstrap"
	echo
	cd I2util
	./bootstrap
	cd ..
	echo
	echo "## Finished I2util/bootstrap"
	echo
fi

set -x
aclocal -I config
autoheader
automake --foreign --add-missing --copy
autoconf
# run configure by hand.
# ./configure $*
