." The first line of this file must contain the '"[e][r][t][v] line
." to tell man to run the appropriate filter "t" for table.
."
."	$Id$
."
."######################################################################
."#									#
."#			   Copyright (C)  2004				#
."#	     			Internet2				#
."#			   All Rights Reserved				#
."#									#
."######################################################################
."
."	File:		owampd.keys.man
."
."	Author:		Jeff Boote
."			Internet2
."
."	Date:		Wed May 12 10:30:01 MDT 2004
."
."	Description:	
."
.TH owampd.keys 5 "$Date$"
.SH NAME
owampd.keys \- One-way latency server AES keyfile database
.SH DESCRIPTION
The \fBowampd.keys\fR file is used to hold the identity/AES keys pairs
needed for \fBowampd\fR to authenticate users. The format of this file
is described in the aespasswd(1) manual page. The location of this
file is controlled by the \fB\-c\fR option to \fBowampd\fR.
.PP
\fBowampd\fR uses symmetric AES keys for authentication. Therefore, the
\fBowping\fR client will have to have access to the exact same AES key
for authentication by AES to work. Most likely, the user will simply
just know the passphrase that generated the AES key in the first place.
Additionally, it is important that the system administrator and end user
ensure the key is not compromised.
.PP
If the \fBowping\fR client is able to authenticate using the identity and AES
key presented, \fBowampd\fR will use the directives found in the
\fBowampd.limits\fR file to map policy restrictions to this connection.
.SH SECURITY CONSIDERATIONS
The keys in the \fBowampd.keys\fR file are not encrypted in any way. The
security of these keys is completely dependent upon the security of the
system and the discretion of the system administrator.
.SH RESTRICTIONS
\fBIdentity\fR names are restricted to 16 characters.
.SH SEE ALSO
aespasswd(1), owping(1), owampd(8), owampd.limits(5),
and the \%http://e2epi.internet2.edu/owamp/ web site.
.SH ACKNOWLEDGMENTS
This material is based in part on work supported by the National Science
Foundation (NSF) under Grant No. ANI-0314723. Any opinions, findings and
conclusions or recommendations expressed in this material are those of
the author(s) and do not necessarily reflect the views of the NSF.
