'\"t
." The first line of this file must contain the '"[e][r][t][v] line
." to tell man to run the appropriate filter "t" for table.
."
."	$Id$
."
."######################################################################
."#									#
."#			   Copyright (C)  2004				#
."#	     			Internet2				#
."#			   All Rights Reserved				#
."#									#
."######################################################################
."
."	File:		owping.1
."
."	Author:		Jeff Boote
."			Internet2
."
."	Date:		Wed Apr 28 08:48:05 MDT 2004
."
."	Description:	
."
.TH owping 1 "$Date$"
.SH NAME
owping \- Client application to request one-way latency tests.
.SH SYNOPSIS
.B owping 
[\fIoptions\fR] peerhost
.SH DESCRIPTION
\fBowping\fR is a command line client application that is used to
initiate one-way latency tests.
.PP
Roundtrip latency measurements (ping) are
an accepted technique to look for network problems. One-way measurements
have the potential to be even more useful. With roundtrip measurements
it is difficult to isolate the direction in which congestion is experienced.
Traffic is often asymmetric with many sites being either primarily producers
or consumers of dtaa. One-way measurements allow more informative
measurements. It is much easier to isolate the effects of traffic on
specific parts of a network.
.PP
.B owping
works by
contacting an \fBowampd\fR daemon on the remote peer host.
\fBowampd\fR manages the resources of the host it runs on.
.PP
The \fBowping\fR client is used to request the type of
test wanted. The parameters allow the user to select the full send schedule,
direction of test (send, receive, or both) as well as packet size.
The results are returned to the client after the test completes. The
test will not be complete until \fItimeout\fR after the last packet is
scheduled to be sent.
.SH OPTIONS
.TP
\fB\-h\fR
.br
Print a usage message and exit.
.RS
.IP Default:
Unset.
.RE
.SS Test Configuration Arguments:
.TP
\fB\-c\fR \fIcount\fR
.br
Number of test packets to send in the test session.
.RS
.IP Default:
100
.RE
.TP
\fB\-f\fR
.br
Perform a One-way test \fBf\fRrom the target \fIpeerhost\fR.
.RS
.IP Default:
True, unless the \fI\-t\fR or \fI\-T\fR have been specified.
.RE
.TP
\fB\-F\fR \fIfromfile\fR
.br
Perform a One-way test \fBf\fRrom the target \fIpeerhost\fR, and
save the results in \fIfromfile\fR.
.RS
.IP Default:
Unset.
.RE
.TP
\fB\-i\fR \fIwait\fR
.br
Wait \fIwait\fR seconds between sending packets. This wait period is not
a fixed value. The actual \fIwait\fR time between each packet is
determined using using a pseudo-poisson function. The amount of time
between each packet will average \fIwait\fR seconds.
.RS
.IP Default:
0.1 (seconds)
.RE
.TP
\fB\-L\fR \fItimeout\fR
.br
Amount of time to wait for a packet to be received before declaring it
lost. As such, it is also the amount of time the test session has to
stay active after the last packet is sent to be able to count duplicate
packets. i.e. Add this number to the duration of your session to determine
how long to expect a test session to take.

Note: The default of 2 seconds longer than a round-trip estimate was simply
a guess for how long a typical user would be willing to wait after the end
of the test for the results. For the \fBOWAMP\fR results to be
statistically relevant and to be able to compare data between two sessions
the \fItimeout\fR option should be specified.
.RS
.IP Default:
2 seconds longer than the round-trip estimate. (seconds)
.RE
.TP
\fB\-s\fR \fIsize\fR
.br
Size of the padding to add to each minimally sized test packet. The minimal
size for a test packet in \fIopen\fR mode is 14 bytes. The minimal size
for a test packet in \fIauthenticated\fR or \fIencrypted\fR mode is 32 bytes.
.RS
.IP Default:
0 (bytes)
.RE
.TP
\fB\-t\fR
.br
Perform a One-way test \fBt\fRoward the target \fIpeerhost\fR.
.RS
.IP Default:
True, unless the \fI\-f\fR or \fI\-F\fR have been specified.
.RE
.TP
\fB\-T\fR \fItofile\fR
.br
Perform a One-way test \fBt\fRoward the target \fIpeerhost\fR, and
save the results in \fItofile\fR.
.RS
.IP Default:
Unset.
.RE
.SS Connection/Authentication Arguments:
.TP
\fB\-A\fR \fIauthmode\fB
.br
Specify the authentication modes the client is willing to use for
communication. \fIauthmode\fR should be set as a character string with
any or all of the characters "AEO". The modes are:
.RS
.IP \fBA\fR
[\fBA\fR]uthenticated. This mode encrypts the control connection and
digitally signs part of each test packet.
.IP \fBE\fR
[\fBE\fR]ncrypted. This mode encrypts the control connection and
encrypts the all of each test packet. (This mode forces an encryption step
between the fetching of a timestamp and when the packet is sent. This
adds more computational delay to the time reported by \fBOWAMP\fR for each
packet.)
.IP \fBO\fR
[\fBO\fR]pen. No encryption of any kind is done.
.PP
The client can specify all the modes with which it is willing to communicate.
The most strict mode that both the server and the client are willing to use
will be selected. Authenticated and Encrypted modes require a "shared secret"
in the form of an AES key.
.IP Default:
"AEO".
.RE
.TP
\fB\-k\fR \fIkeyfile\fR
.br
Indicates that \fBowping\fR should use the AES key in \fIkeyfile\fR for
\fIusername\fB. \fIusername\fR must have a valid key in \fIkeyfile\fR.
\fIkeyfile\fR should have been generated using the aespasswd(1)
application.
.RS
.IP Default:
Unset. (If the \fB\-U\fR option was specified, user will be prompted for a
\fIpassphrase\fR.)
.RE
.TP
\fB\-S\fR \fIsrcaddr\fR
.br
Bind the local address of the client socket to \fIsrcaddr\fR. \fIsrcaddr\fR
can be specified using a DNS name or using standard textual notations for
the IP addresses.
.RS
.IP Default:
Unspecified (wild-card address selection).
.RE
.TP
\fB\-u\fR \fIusername\fR
.br
Specify the username that is used to identify the AES key for
authenticated or encrypted modes. If the \fB\-k\fR option is specified,
the key is retrieved from the \fIkeyfile\fR, otherwise \fBowping\fR prompts
the user for a \fIpassphrase\fR. The \fIpassphrase\fR is used to generate
the AES key.
.RS
.IP Default:
Unset.
.RE
.SS Output Arguments:
.TP
\fB\-a\fR \fIpercentile\fR
.br
Specify an additional \fIpercentile\fR to print out in addition to the 
minimum and the median when printing summary statistics.
.RS
.IP Default:
Unset.
.RE
.TP
\fB\-Q\fR
.br
Suppress the printing of summary statistics.
.RS
.IP Default:
Unset.
.RE
.TP
\fB\-R\fR
.br
Print individual packet records one per line in the raw format:
.RS
.PP
\fISEQNO SENDTIME SSYNC SERR RECVTIME RSYNC RERR\fR
.br
.TS
li l .
SEQNO	Sequence Number.
SENDTIME	Send timestamp.
SSYNC	Sending system synchronized (0 or 1).
SERR	Estimate of SENDTIME error.
RECVTIME	Receive timestamp.
RSYNC	Receiving system synchronized (0 or 1).
RERR	Estimate of RECVTIME error.
.TE
.PP
The timestamps are ASCII representation of 64 bit integers with the
high-order 32 bits representing the number of seconds since Jan 1, 1900
and the low-order 32 bits representing fractional seconds.
.PP
(Implies \fI\-Q\fR.)
.IP Default:
Unset.
.RE
.TP
\fB\-v\fR
.br
Print delays for individual packet records.
.RS
.IP Default:
Unset.
.RE
.SH EXAMPLES
.LP
\fBowping somehost.com\fR
.IP
Run two concurrent ~10 second test sessions at a rate of a packet every 0.1
seconds. One session sending packets from the local host to somehost.com,
the other session receiving packets from somehost.com.) Print summary
statistics of the results only.
.LP
\fBowping -f somehost.com\fR
.IP
Run a single ~10 second test session at a rate of one packet every 0.1
seconds with the packets being sent from somehost.com and received
at the local host.
.LP
\fBowping -F savefile.owp somehost.com\fR
.IP
Same as the previous example, with the resulting data saved in
savefile.owp. The \fBowstats\fR program can be used to decode
that datafile.
.LP
\fBowping -F from.owp -T to.owp somehost.com\fR
.IP
Same as the first example, with the resulting data saved in from.owp and
to.owp.
.LP
\fBowping -U someuser somehost.com\fR
.IP
Run the default test as in the first example. Authenticate using
the identity \fIsomeuser\fR. \fBowping\fR will prompt for a \fIpassphrase\fR.
.SH SEE ALSO
owampd(8), owstats(1), owfetch(1) and the \%http://e2epi.internet2.edu/owamp/
web sites.
.SH ACKNOWLEDGMENTS
This material is based in part on work supported by the National Science
Foundation (NSF) under Grant No. ANI-0314723. Any opinions, findings and
conclusions or recommendations expressed in this material are those of
the author(s) and do not necessarily reflect the views of the NSF.
