.TH owping 1 "$Date$"
." The first line of this file must contain the '"[e][r][t][v] line
." to tell man to run the appropriate filter "t" for table.
."
."	$Id$
."
."######################################################################
."#									#
."#			   Copyright (C)  2004				#
."#	     			Internet2				#
."#			   All Rights Reserved				#
."#									#
."######################################################################
."
."	File:		owping.1
."
."	Author:		Jeff Boote
."			Internet2
."
."	Date:		Wed Apr 28 08:48:05 MDT 2004
."
."	Description:	
."
.SH NAME
owping \- Client application to request one-way latency tests.
.SH SYNOPSIS
.B owping 
[\fIoptions\fR] peerhost
.SH DESCRIPTION
\fBowping\fR is a command line client application that is used to
initiate one-way latency tests.
.PP
Roundtrip latency measurements (ping) are
an accepted technique to look for network problems. One-way measurements
have the potential to be even more useful. With roundtrip measurements
it is difficult to isolate the direction in which congestion is experienced.
Traffic is often asymmetric with many sites being either primarily producers
or consumers of dtaa. One-way measurements allow more informative
measurements. It is much easier to isolate the effects of traffic on
specific parts of a network.
.PP
.B owping
works by
contacting an \fBowampd\fR daemon on the remote peer host.
\fBowampd\fR manages the resources of the host it runs on.
.PP
The \fBowping\fR client is used to request the type of
test wanted. The parameters allow the user to select the full send schedule,
direction of test (send, receive, or both) as well as packet size.
The results are returned to the client after the test completes. The
test will not be complete until \fItimeout\fR after the last packet is
scheduled to be sent.
.SH OPTIONS
.SS Test Configuration Arguments:
.TP
\fB\-f\fR
.br
Perform a One-way test \fBf\fRrom the target \fIpeerhost\fR.
.RS
.IP Default:
True, unless the \fI\-t\fR or \fI\-T\fR have been specified.
.RE
.TP
\fB\-F\fR \fIfromfile\fR
.br
Perform a One-way test \fBf\fRrom the target \fIpeerhost\fR, and
save the results in \fIfromfile\fR.
.RS
.IP Default:
Unset.
.RE
.TP
\fB\-t\fR
.br
Perform a One-way test \fBt\fRoward the target \fIpeerhost\fR.
.RS
.IP Default:
True, unless the \fI\-f\fR or \fI\-F\fR have been specified.
.RE
.TP
\fB\-T\fR \fItofile\fR
.br
Perform a One-way test \fBt\fRoward the target \fIpeerhost\fR, and
save the results in \fItofile\fR.
.RS
.IP Default:
Unset.
.RE
.TP
\fB\-c\fR \fIcount\fR
.br
Number of test packets to send in the test session.
.RS
.IP Default:
100
.RE
.TP
\fB\-i\fR \fIwait\fR
.br
Wait \fIwait\fR seconds between sending packets. This wait period is not
a fixed value. The actual \fIwait\fR time between each packet is
determined using using a pseudo-poisson function. The amount of time
between each packet will average \fIwait\fR seconds.
.RS
.TP Default:
0.1 (seconds)
.RE
.TP
\fB\-s\fR \fIsize\fR
Size of the padding to add to each minimally sized test packet. The minimal
size for a test packet in \fIopen\fR mode is 14 bytes. The minimal size
for a test packet in \fIauthenticated\fR or \fIencrypted\fR mode is 32 bytes.
.RS
.TP Default:
0 (bytes)
.RE

.TP
\fB\-b\fR \fIbandwidth\fR
Limit UDP send rate to \fIbandwidth\fR (bits/sec).
.RS
.IP Default:
1 Mb.
.RE
.TP
\fB\-i\fR \fIinterval\fR
Report interval (seconds).
.RS
.IP Default:
unset (no intervals reported).
.RE
.TP
\fB\-l\fR \fIlen\fR
length of read/write buffers (bytes).
.RS
.IP Default:
8 KB TCP, 1470 bytes UDP.
.RE
.TP
\fB\-P\fR \fInThreads\fR
Generates an error message. The \fB\-P\fR option of \fBIperf\fR is not
currently supported by \fBowping\fR.
.TP
\fB\-S\fR \fITOS\fR
Generates an error message. The \fB\-S\fR option of \fBIperf\fR is not
currently supported by \fBowping\fR.
.TP
\fB\-t\fR \fItime\fR
Duration of test (seconds).
.RS
.IP Default:
10.
.RE
.TP
\fB\-u\fR
UDP test.
.RS
.IP Default:
TCP test.
.RE
.TP
\fB\-W\fR \fIwindow\fR
Same as the \fB\-w\fR option, except that the value is advisory. \fBowping\fR
will attempt to dynamically determine the appropriate TCP window, based upon
RTT information gathered from the control socket. If \fBowping\fR is unable
to dynamically determine a window, the value \fIwindow\fR will be used.
.RS
.IP Default:
Unset (system defaults).
.RE
.TP
\fB\-w\fR \fIwindow\fR
Socket buffer sizes (bytes). For TCP, this sets the TCP window size. For UDP,
this sets the socket receive buffer size.
.RS
.IP Default:
Unset (system defaults).
.RE
.SS Scheduling Arguments:
.TP
\fB\-I\fR \fIinterval\fR
Specifies that \fBowping\fR should attempt to run the \fBIperf\fR test every
\fIinterval\fR seconds.
.RS
.IP Default:
Unset. If it is unset, \fBowping\fR only runs the test once.
.RE
.TP
\fB\-L\fR \fIlatest\fR
Specifies the latest time the client is willing to wait for a
reservation window. When \fBowping\fR requests a test from the \fBowpingd\fR
server, it specifies the earliest time and the latest time it is willing
to accept. The \fIlatest\fR option is specified as a number of seconds
that will be added to the start time.
.RS
.IP Default:
If \fIinterval\fR is set, the default is 50% of \fIinterval\fR. Otherwise,
the default is twice the test duration \fItime\fR. (See \fB\-t\fR).
.RE
.TP
\fB\-n\fR \fInIntervals\fR
Number of tests to perform if the \fB\-I\fR option is set.
.RS
.IP Default:
Continuous.
.RE
.TP
\fB\-R\fR \fIalpha\fR
Randomize the start time of the test within this \fIalpha\fR percent of the
\fIinterval\fR. Valid values for \fIalpha\fR are from 0\-50. \fBowping\fR
will attempt to run the test every \fIinterval\fR +/\- \fIalpha\fR percent.
For example, if the \fIinterval\fR is 300 seconds and \fIalpha\fR is
set to 10 percent, then \fBowping\fR will attempt to run a test every
270\-330 seconds. This option is only useful with the \fB\-I\fR option.
.RS
.IP Default:
0 (no randomness).
.RE
.SS Connection/Authentication Arguments:
.TP
\fB\-A\fR \fIauthmode\fB
Specify the authentication modes the client is willing to use for
communication. \fIauthmode\fR should be set as a character string with
any or all of the characters "AEO". The modes are:
.RS
.IP \fBA\fR
[\fBA\fR]uthenticated. This mode encrypts the control connection.
.IP \fBE\fR
[\fBE\fR]ncrypted. This mode encrypts the control connection. If the
test supports encryption, this mode will additionally encrypt the test
stream. (Encryption of the test stream is not currently supported, so
this mode is currently identical to authenticated.)
.IP \fBO\fR
[\fBO\fR]pen. No encryption of any kind is done.
.PP
The client can specify all the modes with which it is willing to communicate. The
most strict mode that both the server and the client are willing to use
will be selected.
.IP Default:
"AEO".
.RE
.TP
\fB\-B\fR \fIsrcaddr\fR
Bind the local address of the client socket to \fIsrcaddr\fR. \fIsrcaddr\fR
can be specified using a DNS name or using standard textual notations for
the IP addresses.
.RS
.IP Default:
Unspecified (wild-card address selection).
.RE
.TP
\fB\-k\fR \fIkeyfile\fR
Indicates that \fBowping\fR should use the AES key in \fIkeyfile\fR for
\fIusername\fB. \fIusername\fR must have a valid key in \fIkeyfile\fR.
\fIkeyfile\fR should have been generated using the aespasswd(1)
application.
.RS
.IP Default:
Unset. (If the \fB\-U\fR option was specified, user will be prompted for a
\fIpassphrase\fR.)
.RE
.TP
\fB\-U\fR \fIusername\fR
Specify the username that is used to identify the AES key for
authenticated or encrypted modes. If the \fB\-k\fR option is specified,
the key is retrieved from the \fIkeyfile\fR, otherwise \fBowping\fR prompts
the user for a \fIpassphrase\fR. The \fIpassphrase\fR is used to generate
the AES key.
.RS
.IP Default:
Unset.
.RE
.SS Output Arguments:
.TP
\fB\-d\fR \fIdir\fR
Specifies directory for results files if the \fB\-p\fR option is set.
.TP
\fB\-e\fR \fIfacility\fR
Syslog \fIfacility\fR to log messages to.
.RS
.IP Default:
LOG_USER.
.RE
.TP
\fB\-h\fR
Print a help message.
.TP
\fB\-p\fR
Place \fBIperf\fR results in files. Print the filenames to stdout when
results are complete.
.TP
\fB\-q\fR
Quiet output. Output as little as possible.
.TP
\fB\-r\fR
Send syslog messages to stderr.  This is the default unless the \fB\-q\fR
option is specified so this option is only useful with the \fB\-q\fR
option.
.TP
\fB\-V\fR
Print version information and exit.
.TP
\fB\-v\fR
Verbose output. Specifying additional \fB\-v\fR's increases the verbosity.
.TP
\fB\-x\fR
Output sender (\fBIperf\fR client) results as well as receiver results.
By default, sender results are not output. If the \fB\-p\fR option is
specified, the sender results are placed in an additional file.
.SH LIMITATIONS
Currently it is only possible to specify either the \fBIperf\fR
sender or the \fBIperf\fR receiver on the command line. The local
host is assumed to be the other endpoint of the test.
.PP
Works with versions 1.7.0 and 2.0.b of \fBIperf\fR.
.SH EXAMPLES
.LP
\fBowping -c somehost.com\fR
.IP
Run a default 10 second TCP \fBIperf\fR test as soon as possible with
localhost as the sender and somehost.com as the receiver. Return
the results from the receive side of the test.
.LP
\fBowping -x -c somehost.com\fR
.IP
Like the previous test, but also return the results from the sender
side of the test.
.LP
\fBowping -t 30 -s somehost.com\fR
.IP
Run a 30 second TCP \fBIperf\fR test with somehost.com as the sender
and localhost as the receiver.
.LP
\fBowping -I 3600 -R 10 -t 10 -u -b 10m -s somehost.com\fR
.IP
Run a 10 second UDP test about every hour (3600 +/- 360 seconds) with
the sender rate limited to 10 Mbits per second from somehost.com to
localhost.
.LP
\fBowping -U someuser -s somehost.com\fR
.IP
Run the default 10 second TCP \fBIperf\fR test. Authenticate using
the identity \fIsomeuser\fR. \fBowping\fR will prompt for a \fIpassphrase\fR.
.SH SEE ALSO
owampd(8) and the \%http://e2epi.internet2.edu/owamp/
and \%http://dast.nlanr.net/Projects/Iperf/ web sites.
.SH ACKNOWLEDGMENTS
This material is based in part on work supported by the National Science
Foundation (NSF) under Grant No. ANI-0314723. Any opinions, findings and
conclusions or recommendations expressed in this material are those of
the author(s) and do not necessarily reflect the views of the NSF.
