#! /usr/bin/dh-exec
usr/share/man/man5/owamp-server.conf.5
usr/share/man/man5/owamp-server.limits.5
usr/share/man/man5/owamp-server.pfs.5
usr/share/man/man8/owampd.8
usr/bin/owampd usr/sbin
conf/owampd.limits => etc/owamp-server/owamp-server.limits
conf/owampd.rpm.conf => etc/owamp-server/owamp-server.conf
conf/owampd-cleanup => etc/cron.daily/owamp-server
debian/apparmor/usr.sbin.owampd etc/apparmor.d
